---

- name: Ensure OpenVPN is installed
  apt:
    name: openvpn
    state: present
    install_recommends: False

- name: Generate Diffie Hellman parameters
  command: openssl dhparam -text -out dh{{openvpn_dh_param_size}}.pem {{openvpn_dh_param_size}}
  args:
    chdir: /etc/openvpn/
    creates: dh{{openvpn_dh_param_size}}.pem

- name: Ensure filemode for Diffie Hellman parameters file
  file:
    name: /etc/openvpn/dh{{openvpn_dh_param_size}}.pem
    mode: 0644

- name: Generate OpenVPN configurations
  template:
    src: 'etc/openvpn/openvpn.conf.j2'
    dest: '/etc/openvpn/{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  with_items: [ '{{ openvpn_connections }}' ]
  notify: [ 'Restart OpenVPN' ]

- name: Remove OpenVPN server configurations if requested
  file:
    dest: '/etc/openvpn/{{ item.name }}.conf'
    state: 'absent'
  with_items: [ '{{ openvpn_connections }}' ]
  notify: [ 'Restart OpenVPN' ]
  when: item.name|default and item.delete|default

- name: Ensure OpenVPN service is enabled
  service:
    name: openvpn
    enabled: True

